export const DESIGN_STYLES = {
  main: 'min-h-screen text-white',
  hero: 'relative w-full section-tone-green pt-24',
  heroInner: 'relative mx-auto grid w-full max-w-6xl gap-12 px-6 pb-20 pt-8 md:grid-cols-[1.1fr_0.9fr] md:items-center md:gap-16 md:pb-28 md:pt-12',
  heroText: '',
  heroMedia: 'mx-auto w-full max-w-sm md:max-w-none',
  heroTitle: 'text-4xl font-semibold leading-[1.15] tracking-tight md:text-5xl lg:text-[3.25rem]',
  heroSubtitle: 'mt-2 block text-3xl font-normal text-white/72 md:text-4xl lg:text-[2.65rem]',
  heroLead: 'mt-8 max-w-xl text-lg leading-8 text-white/78',
  heroCta: 'mt-10 flex flex-col items-start gap-4',
  photoWrap: 'overflow-hidden rounded-[1.75rem] shadow-[0_24px_80px_rgba(0,0,0,0.35)]',
  photo: 'block max-h-[30rem] w-full object-cover object-[center_22%] md:max-h-[34rem]',
  caption: 'mt-4 text-center text-sm text-white/70 md:text-left',
  section: 'relative w-full border-t border-white/10',
  sectionInner: 'relative mx-auto w-full max-w-6xl px-6 py-20 md:py-24',
  heading: 'text-3xl font-semibold leading-tight md:text-4xl',
  headingWrap: 'max-w-3xl',
  body: 'text-base leading-8 text-white/76',
  quoteGrid: 'mt-10 grid gap-4 md:grid-cols-2',
  quoteItem: 'rounded-2xl border border-[var(--color-accent-border-soft)] bg-[#15241d] px-6 py-5 text-lg leading-8 text-white/88',
  quoteHover: 'transition-all duration-300 ease-out hover:-translate-y-1 hover:border-[var(--color-accent-border)] hover:bg-[#1a2e25] hover:shadow-[0_10px_30px_rgba(0,0,0,0.15)]',
  phraseHover: 'transition-all duration-300 ease-out hover:-translate-y-1 hover:border-white/16 hover:bg-white/[0.06] hover:shadow-[0_10px_30px_rgba(0,0,0,0.15)]',
  lineHover: 'transition-all duration-300 ease-out hover:-translate-y-1 hover:border-[var(--color-accent)] hover:bg-white/[0.03] hover:pl-6',
  practicalGrid: 'mt-8 grid gap-5 md:grid-cols-2',
  practicalItem: 'border-l border-[var(--color-accent-border)] pl-5 text-base leading-8 text-white/78',
  stepList: 'mt-12 space-y-4',
  stepItem: 'grid gap-4 rounded-2xl border border-[var(--color-accent-border-soft)] bg-[#15241d] p-6 md:grid-cols-[3rem_1fr]',
  denyItem: 'min-h-16 border-l-2 border-[var(--color-accent-border-soft)] pl-5 text-lg leading-8 text-white/82',
  faqItem: 'max-w-3xl border-b border-white/8 pb-10 last:border-b-0 last:pb-0',
  closing: 'border-b border-white/10 pb-24',
  quemSouGrid: 'grid gap-12 md:grid-cols-[0.85fr_1.15fr] md:items-start',
  profileFrame: 'overflow-hidden rounded-[1.75rem] border border-white/10 bg-[var(--color-surface)]',
}
