export const DESIGNS = [
  { id: 'classic', label: 'Clássico', preview: 'classic' },
  { id: 'editorial', label: 'Editorial', preview: 'editorial' },
  { id: 'cards', label: 'Cards', preview: 'cards' },
  { id: 'minimal', label: 'Minimal', preview: 'minimal' },
]

export const DEFAULT_DESIGN = 'classic'

export const DESIGN_STYLES = {
  classic: {
    main: 'min-h-screen pt-24 text-white',
    hero: 'mx-auto grid w-full max-w-6xl gap-12 px-6 pb-20 pt-8 md:grid-cols-[1.1fr_0.9fr] md:items-center md:gap-16 md:pb-28 md:pt-12',
    heroText: '',
    heroMedia: 'mx-auto flex w-full max-w-sm items-start gap-2 md:max-w-none',
    heroTitle: 'text-4xl font-semibold leading-[1.15] tracking-tight md:text-5xl lg:text-[3.25rem]',
    heroSubtitle: 'mt-2 block text-3xl font-normal text-white/72 md:text-4xl lg:text-[2.65rem]',
    heroLead: 'mt-8 max-w-xl text-lg leading-8 text-white/78',
    heroCta: 'mt-10 flex flex-col items-start gap-4',
    photoWrap: 'overflow-hidden rounded-[1.75rem] shadow-[0_24px_80px_rgba(0,0,0,0.35)]',
    photo: 'block max-h-[30rem] w-full object-cover object-[center_22%] md:max-h-[34rem]',
    caption: 'mt-4 text-center text-sm text-white/70 md:text-left',
    section: 'mx-auto w-full max-w-6xl border-t border-white/10 px-6 py-20 md:py-24',
    heading: 'text-3xl font-semibold leading-tight md:text-4xl',
    headingWrap: 'max-w-3xl',
    body: 'text-base leading-8 text-white/76',
    quoteGrid: 'mt-10 grid gap-4 md:grid-cols-2',
    quoteItem: 'rounded-2xl border border-white/8 bg-white/[0.03] px-6 py-5 text-lg leading-8 text-white/88',
    practicalGrid: 'mt-8 grid gap-5 md:grid-cols-2',
    practicalItem: 'border-l border-[var(--color-accent-border)] pl-5 text-base leading-8 text-white/78',
    stepList: 'mt-12 space-y-10',
    denyItem: 'border-l-2 border-[var(--color-accent-border-soft)] pl-5 text-lg leading-8 text-white/82',
    faqItem: 'max-w-3xl border-b border-white/8 pb-10 last:border-b-0 last:pb-0',
    closing: 'border-b border-white/10 pb-24',
    quemSouGrid: 'grid gap-12 md:grid-cols-[0.85fr_1.15fr] md:items-start',
    profileFrame: 'overflow-hidden rounded-[1.75rem] border border-white/10 bg-[var(--color-surface)] transition-[background] duration-400',
  },
  editorial: {
    main: 'min-h-screen pt-24 text-white',
    hero: 'mx-auto flex w-full max-w-3xl flex-col items-center gap-12 px-6 pb-24 pt-8 text-center md:pb-32 md:pt-12',
    heroText: 'order-1 w-full',
    heroMedia: 'order-2 flex items-start justify-center gap-2',
    heroTitle: 'text-4xl font-semibold leading-[1.12] tracking-tight md:text-5xl lg:text-6xl',
    heroSubtitle: 'mt-3 block text-2xl font-normal text-white/70 md:text-3xl',
    heroLead: 'mt-8 mx-auto max-w-2xl text-lg leading-8 text-white/76',
    heroCta: 'mt-10 flex flex-col items-center gap-4',
    photoWrap: 'overflow-hidden rounded-[1.75rem] shadow-[0_24px_80px_rgba(0,0,0,0.35)]',
    photo: 'block max-h-[32rem] w-full scale-[1.08] object-cover object-[center_18%] md:max-h-[36rem]',
    caption: 'mt-2 text-sm text-white/65',
    section: 'mx-auto w-full max-w-3xl border-t border-white/8 px-6 py-24 text-center md:py-28',
    heading: 'mx-auto text-3xl font-semibold leading-tight md:text-4xl',
    headingWrap: 'max-w-2xl mx-auto',
    body: 'mx-auto max-w-2xl text-base leading-8 text-white/74',
    quoteGrid: 'mt-10 space-y-6 text-left',
    quoteItem: 'border-l-2 border-[var(--color-accent-border)] pl-5 text-lg leading-8 text-white/86 italic',
    practicalGrid: 'mt-8 space-y-5 text-left',
    practicalItem: 'border-l border-[var(--color-accent-border)] pl-5 text-base leading-8 text-white/76',
    stepList: 'mt-12 space-y-12 text-left',
    denyItem: 'border-l-2 border-[var(--color-accent-border-soft)] pl-5 text-lg leading-8 text-white/80 text-left',
    faqItem: 'mx-auto max-w-2xl border-b border-white/8 pb-10 text-left last:border-b-0 last:pb-0',
    closing: 'border-b border-white/10 pb-24',
    quemSouGrid: 'flex flex-col items-center gap-10 text-left md:flex-col',
    profileFrame: 'mx-auto overflow-hidden rounded-[1.75rem] border border-white/10 bg-[var(--color-surface)]',
  },
  cards: {
    main: 'min-h-screen space-y-6 px-4 pb-12 pt-24 text-white md:space-y-8 md:px-6',
    hero: 'mx-auto grid w-full max-w-6xl gap-10 rounded-[2rem] border border-white/10 bg-[var(--color-surface)] p-6 shadow-[0_24px_80px_rgba(0,0,0,0.25)] md:grid-cols-[1.05fr_0.95fr] md:items-center md:gap-12 md:p-10',
    heroText: '',
    heroMedia: 'mx-auto flex w-full max-w-sm items-start gap-2 md:max-w-none',
    heroTitle: 'text-4xl font-semibold leading-[1.15] tracking-tight md:text-5xl',
    heroSubtitle: 'mt-2 block text-3xl font-normal text-white/72 md:text-4xl',
    heroLead: 'mt-8 max-w-xl text-lg leading-8 text-white/78',
    heroCta: 'mt-10 flex flex-col items-start gap-4',
    photoWrap: 'overflow-hidden rounded-[1.5rem] border border-white/10',
    photo: 'block max-h-[28rem] w-full object-cover object-[center_22%] md:max-h-[32rem]',
    caption: 'mt-4 text-center text-sm text-white/70 md:text-left',
    section: 'mx-auto w-full max-w-6xl rounded-[2rem] border border-white/10 bg-[var(--color-surface)] px-6 py-12 shadow-[0_16px_50px_rgba(0,0,0,0.2)] md:px-10 md:py-16',
    heading: 'text-3xl font-semibold leading-tight md:text-4xl',
    headingWrap: 'max-w-3xl',
    body: 'text-base leading-8 text-white/76',
    quoteGrid: 'mt-10 grid gap-4 md:grid-cols-2',
    quoteItem: 'rounded-xl border border-white/10 bg-white/[0.04] px-5 py-4 text-lg leading-8 text-white/88',
    practicalGrid: 'mt-8 grid gap-4 md:grid-cols-2',
    practicalItem: 'rounded-xl border border-white/8 bg-white/[0.03] p-5 text-base leading-8 text-white/78',
    stepList: 'mt-10 space-y-6',
    denyItem: 'rounded-xl border border-white/8 bg-white/[0.03] px-5 py-4 text-lg leading-8 text-white/82',
    faqItem: 'max-w-3xl rounded-xl border border-white/8 bg-white/[0.03] px-5 py-5',
    closing: 'pb-8',
    quemSouGrid: 'grid gap-10 md:grid-cols-[0.85fr_1.15fr] md:items-start',
    profileFrame: 'overflow-hidden rounded-[1.5rem] border border-white/10 bg-[var(--color-bg)]',
  },
  minimal: {
    main: 'min-h-screen pt-24 text-white',
    hero: 'mx-auto grid w-full max-w-4xl gap-10 px-6 pb-16 pt-8 md:grid-cols-[1fr_0.85fr] md:items-end md:gap-12 md:pb-20 md:pt-10',
    heroText: '',
    heroMedia: 'mx-auto flex w-full max-w-sm items-start gap-2 md:max-w-none',
    heroTitle: 'text-3xl font-medium leading-[1.2] tracking-tight md:text-4xl lg:text-[2.75rem]',
    heroSubtitle: 'mt-2 block text-2xl font-normal text-white/65 md:text-3xl',
    heroLead: 'mt-6 max-w-lg text-base leading-7 text-white/72',
    heroCta: 'mt-8 flex flex-col items-start gap-3',
    photoWrap: 'overflow-hidden rounded-xl',
    photo: 'block max-h-[26rem] w-full object-cover object-[center_22%] md:max-h-[30rem]',
    caption: 'mt-3 text-left text-xs uppercase tracking-[0.2em] text-white/50',
    section: 'mx-auto w-full max-w-4xl px-6 py-14 md:py-16',
    heading: 'text-2xl font-medium leading-tight md:text-3xl',
    headingWrap: 'max-w-2xl',
    body: 'text-base leading-7 text-white/72',
    quoteGrid: 'mt-8 space-y-5',
    quoteItem: 'text-base leading-7 text-white/80',
    practicalGrid: 'mt-6 space-y-4',
    practicalItem: 'text-base leading-7 text-white/72 before:mr-2 before:text-[var(--color-accent)] before:content-["—"]',
    stepList: 'mt-8 space-y-8',
    denyItem: 'text-base leading-7 text-white/78 before:mr-2 before:text-[var(--color-accent)] before:content-["—"]',
    faqItem: 'max-w-2xl border-t border-white/8 pt-8 first:border-t-0 first:pt-0',
    closing: 'pb-20',
    quemSouGrid: 'grid gap-8 md:grid-cols-[0.75fr_1.25fr] md:items-start',
    profileFrame: 'overflow-hidden rounded-xl',
  },
}
