export const DESIGN_STYLES = {
  main: 'min-h-screen text-white',
  hero: 'relative w-full section-tone-green pt-24',
  heroInner: 'relative mx-auto grid w-full max-w-6xl gap-12 px-6 pb-20 pt-8 md:grid-cols-[1.1fr_0.9fr] md:items-center md:gap-16 md:pb-28 md:pt-12',
  heroText: '',
  heroMedia: 'mx-auto w-full max-w-sm md:max-w-none',
  heroTitle: 'text-4xl font-semibold leading-[1.15] tracking-tight md:text-5xl lg:text-[3.25rem]',
  heroSubtitle: 'mt-2 block text-3xl font-normal text-white/72 md:text-4xl lg:text-[2.65rem]',
  heroLead: 'mt-8 max-w-xl text-lg leading-8 text-white/78 text-justify',
  heroCta: 'mt-10 flex flex-col items-start gap-4',
  photoWrap: 'overflow-hidden rounded-[1.75rem] shadow-[0_24px_80px_rgba(0,0,0,0.35)]',
  photo: 'block max-h-[30rem] w-full object-cover object-[center_22%] md:max-h-[34rem]',
  caption: 'mt-4 text-center text-sm text-white/70 md:text-left',
  section: 'relative w-full border-t border-white/10',
  sectionInner: 'relative mx-auto w-full max-w-6xl px-6 py-20 md:py-24',
  heading: 'text-3xl font-semibold leading-tight md:text-4xl',
  headingWrap: 'max-w-3xl',
  body: 'text-base leading-8 text-white/76 text-justify',
  helper: 'max-w-md text-sm leading-7 text-white/58 text-justify',
  quoteGrid: 'mt-10 grid gap-4 md:grid-cols-2',
  quoteItem: 'rounded-2xl border border-[var(--color-accent-border-soft)] bg-[#15241d] px-6 py-5 text-lg leading-8 text-white/88 text-justify',
  quoteHover: 'transition-all duration-300 ease-out hover:-translate-y-1 hover:border-[var(--color-accent-border)] hover:bg-[#1a2e25] hover:shadow-[0_10px_30px_rgba(0,0,0,0.15)]',
  phraseHover: 'transition-all duration-300 ease-out hover:-translate-y-1 hover:border-white/16 hover:bg-white/[0.06] hover:shadow-[0_10px_30px_rgba(0,0,0,0.15)]',
  practicalGrid: 'mt-8 grid gap-4 md:grid-cols-2',
  practicalItem: 'group flex items-start gap-4 rounded-xl border border-transparent px-4 py-3 transition-all duration-300 ease-out hover:-translate-y-0.5 hover:border-[var(--color-accent-border)] hover:bg-white/[0.05] hover:shadow-[0_8px_24px_rgba(0,0,0,0.18)]',
  practicalCheck: 'mt-1 flex h-5 w-5 shrink-0 items-center justify-center rounded-[0.3rem] border border-[var(--color-accent)]/70 bg-[var(--color-accent)]/18 text-[var(--color-accent-light)] shadow-[inset_0_1px_0_rgba(255,255,255,0.08)] transition-all duration-300 group-hover:scale-110 group-hover:border-[var(--color-accent-light)] group-hover:bg-[var(--color-accent)] group-hover:text-[var(--color-bg)] group-hover:shadow-[0_0_12px_rgba(158,196,176,0.35)]',
  practicalText: 'text-base leading-8 text-white/78 text-justify transition-all duration-300 group-hover:text-white group-hover:translate-x-0.5',
  stepList: 'mt-12 space-y-4',
  stepItem: 'grid gap-4 rounded-2xl border border-[var(--color-accent-border-soft)] bg-[#15241d] p-6 md:grid-cols-[3rem_1fr]',
  denyGrid: 'mt-10 max-w-3xl',
  denyItem: 'group grid grid-cols-[2.25rem_1fr] gap-x-5 pb-9 last:pb-0',
  denyRail: 'flex h-full flex-col items-center',
  denyMark: 'relative z-10 flex h-7 w-7 shrink-0 items-center justify-center rounded-full border border-white/20 bg-[var(--color-bg)] text-white/45 transition-all duration-300 group-hover:scale-110 group-hover:border-[var(--color-accent)] group-hover:bg-[var(--color-accent)]/18 group-hover:text-[var(--color-accent-light)] group-hover:shadow-[0_0_16px_rgba(158,196,176,0.38)]',
  denyConnector: 'mt-2 w-px flex-1 min-h-8 bg-gradient-to-b from-[var(--color-accent-border-soft)] to-transparent transition-colors duration-300 group-hover:from-[var(--color-accent)]/70',
  denyText: 'text-base leading-8 text-white/78 text-justify transition-all duration-300 group-hover:text-white group-hover:translate-x-1',
  faqList: 'mt-12 max-w-3xl divide-y divide-white/10 border-y border-white/10',
  faqTrigger: 'flex w-full cursor-pointer items-start justify-between gap-5 py-6 text-left md:py-7',
  faqQuestion:
    'text-[1.05rem] font-medium leading-8 text-white/82 transition-colors duration-300 group-hover:text-white md:text-lg',
  faqQuestionOpen: 'text-white',
  faqToggle:
    'relative mt-1 flex h-8 w-8 shrink-0 items-center justify-center rounded-full border border-white/14 text-[var(--color-accent-light)] transition-all duration-300 group-hover:border-[var(--color-accent)]/50 group-hover:bg-[var(--color-accent)]/10',
  faqToggleOpen:
    'border-[var(--color-accent)]/65 bg-[var(--color-accent)]/16 shadow-[0_0_18px_rgba(158,196,176,0.22)]',
  faqToggleBar: 'absolute h-px w-3 bg-current transition-transform duration-300 ease-out',
  faqAnswerWrap: 'grid grid-rows-[0fr] transition-[grid-template-rows] duration-300 ease-out',
  faqAnswerOpen: 'grid-rows-[1fr]',
  faqAnswer:
    'max-w-2xl space-y-4 pb-7 pr-12 text-base leading-8 text-white/68 opacity-0 translate-y-1 transition-all duration-300 ease-out [&_p]:text-justify',
  faqAnswerVisible: 'opacity-100 translate-y-0',
  closing: 'border-b border-white/10 pb-24',
  quemSouGrid: 'grid gap-12 md:grid-cols-[0.85fr_1.15fr] md:items-start',
  profileFrame: 'overflow-hidden rounded-[1.75rem] border border-white/10 bg-[var(--color-surface)]',
}
